name: 编译 TrackHook 插件
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置环境变量
        run: |
          echo "THEOS=${HOME}/theos" >> $GITHUB_ENV
          echo "PATH=${HOME}/theos/bin:$PATH" >> $GITHUB_ENV

      - name: 安装依赖 + Theos
        run: |
          # 安装签名工具+换行符转换工具
          brew install ldid dos2unix
          # 转换control为Unix换行符（修复核心报错）
          dos2unix control
          # 安装Theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          # 配置Xcode
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: 编译打包 deb
        run: |
          make clean
          make package FINALPACKAGE=1

      - name: 上传DEB插件包
        uses: actions/upload-artifact@v4
        with:
          name: TrackHook_成品插件
          path: packages/*.deb
